-- Supabase Schema Initialization
-- Run this in your Supabase SQL Editor

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    genre TEXT NOT NULL,
    price NUMERIC NOT NULL,
    image TEXT NOT NULL,
    description TEXT NOT NULL,
    display_name TEXT,
    slug TEXT UNIQUE,
    meta_description TEXT,
    alt_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL
);

-- 2. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    items JSONB NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    subtotal NUMERIC NOT NULL,
    shipping_charge NUMERIC NOT NULL,
    total NUMERIC NOT NULL,
    payment_id TEXT,
    payment_method TEXT,
    payment_status TEXT,
    razorpay_order_id TEXT,
    razorpay_signature TEXT,
    tracking_number TEXT,
    courier_name TEXT,
    shipped_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    delivery_method TEXT DEFAULT 'courier',
    cancelled_by TEXT,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL,
    full_name TEXT,
    phone TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3b. Create Addresses Table
CREATE TABLE IF NOT EXISTS public.addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    recipient_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    house TEXT NOT NULL,
    street TEXT,
    landmark TEXT,
    city TEXT,
    state TEXT,
    pincode TEXT,
    country TEXT DEFAULT 'India' NOT NULL,
    address_type TEXT CHECK (address_type IN ('Home', 'Work', 'Other')) NOT NULL,
    is_default BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    CONSTRAINT valid_phone CHECK (phone ~ '^\+?[0-9\s\-()]{10,20}$'),
    CONSTRAINT valid_pincode CHECK (pincode IS NULL OR pincode ~ '^[0-9]{6}$')
);

-- Create performance index
CREATE INDEX IF NOT EXISTS addresses_user_id_idx ON public.addresses(user_id);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies
-- Products: Anyone can view active products. Admins (to be configured) can do all.
CREATE POLICY "Enable read access for all users" ON public.products
    FOR SELECT USING (is_active = true);

-- Orders: Users can read their own orders. Anyone can insert (for guest checkout).
CREATE POLICY "Enable insert for everyone" ON public.orders
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for owners" ON public.orders
    FOR SELECT USING (auth.uid() = user_id);

-- Profiles: Users can read, update, and insert their own profile.
CREATE POLICY "Users can insert own profile" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can view own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Addresses: Users can read, insert, update, and delete their own addresses.
CREATE POLICY "Users can view own addresses" ON public.addresses
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own addresses" ON public.addresses
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own addresses" ON public.addresses
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own addresses" ON public.addresses
    FOR DELETE USING (auth.uid() = user_id);

-- Triggers for Addresses
CREATE OR REPLACE FUNCTION public.set_current_timestamp_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_addresses_updated_at
    BEFORE UPDATE ON public.addresses
    FOR EACH ROW
    EXECUTE PROCEDURE public.set_current_timestamp_updated_at();

CREATE OR REPLACE FUNCTION public.handle_default_address()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_default = true THEN
        UPDATE public.addresses
        SET is_default = false
        WHERE user_id = NEW.user_id AND id <> NEW.id AND is_default = true;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_address_default_changed
    BEFORE INSERT OR UPDATE OF is_default ON public.addresses
    FOR EACH ROW
    WHEN (NEW.is_default = true)
    EXECUTE PROCEDURE public.handle_default_address();

-- 6. Setup Storage Buckets
INSERT INTO storage.buckets (id, name, public) 
VALUES 
  ('posters', 'posters', true),
  ('avatars', 'avatars', true),
  ('assets', 'assets', true),
  ('custom-designs', 'custom-designs', true)
ON CONFLICT (id) DO NOTHING;

-- Allow public access to read files in these buckets
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id IN ('posters', 'avatars', 'assets', 'custom-designs'));

-- Allow authenticated users to upload files to custom-designs (inside uploads/) and avatars
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK (
  (bucket_id = 'custom-designs' AND (storage.foldername(name))[1] = 'uploads' AND auth.role() = 'authenticated') OR
  (bucket_id = 'avatars' AND auth.role() = 'authenticated')
);

-- Allow users to update their own objects
CREATE POLICY "Owner Update" ON storage.objects FOR UPDATE USING (
  auth.uid() = owner
);

-- Allow users to delete their own objects
CREATE POLICY "Owner Delete" ON storage.objects FOR DELETE USING (
  auth.uid() = owner
);

-- 7. Create Wishlists Table
CREATE TABLE IF NOT EXISTS public.wishlists (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- Create Indexes for performance
CREATE INDEX IF NOT EXISTS wishlists_user_id_idx ON public.wishlists(user_id);
CREATE INDEX IF NOT EXISTS wishlists_product_id_idx ON public.wishlists(product_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can view own wishlist" ON public.wishlists
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own wishlist items" ON public.wishlists
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own wishlist items" ON public.wishlists
    FOR DELETE USING (auth.uid() = user_id);

-- 8. Automate Profile Creation on Signup
-- Create a trigger function that automatically inserts a profile entry when a user is created in auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name)
    VALUES (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data->>'full_name', '')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop the trigger if it already exists to prevent duplicates
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Bind the trigger to run after new user insertion
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 9. Create Coupons Table
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('percentage', 'fixed', 'buy_x_get_y', 'percentage_discount')) NOT NULL,
    value NUMERIC,
    buy_qty INTEGER,
    free_qty INTEGER,
    min_subtotal NUMERIC,
    min_quantity INTEGER,
    description TEXT NOT NULL,
    min_order_value NUMERIC,
    discount_percent NUMERIC,
    is_active BOOLEAN DEFAULT true NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    max_redemptions INTEGER,
    current_redemptions INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Create Coupon Users Table (For user-specific coupons)
CREATE TABLE IF NOT EXISTS public.coupon_users (
    coupon_id BIGINT REFERENCES public.coupons(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (coupon_id, user_id)
);

-- Enable RLS
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_users ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Anyone can view coupons" ON public.coupons
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage coupons" ON public.coupons
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_admin = true
        )
    );

CREATE POLICY "Users can view their own eligibility" ON public.coupon_users
    FOR SELECT USING (auth.uid() = user_id OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND is_admin = true
    ));

CREATE POLICY "Admins can manage coupon users" ON public.coupon_users
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_admin = true
        )
    );




