-- Migration: Create Visitor Analytics Tables, Functions, and Policies
-- Description: Lightweight first-party visitor session tracking & admin analytics
-- Created: 2026-09-20

-- 1. Create visitor_sessions table
CREATE TABLE IF NOT EXISTS public.visitor_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT UNIQUE NOT NULL,
    first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_visitor_sessions_last_seen ON public.visitor_sessions(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_visitor_sessions_session_id ON public.visitor_sessions(session_id);

-- 2. Create visitor_daily_visits table
CREATE TABLE IF NOT EXISTS public.visitor_daily_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    visit_date DATE DEFAULT (timezone('utc'::text, now()))::date NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT visitor_daily_visits_session_date_unique UNIQUE (session_id, visit_date)
);

CREATE INDEX IF NOT EXISTS idx_visitor_daily_visits_date ON public.visitor_daily_visits(visit_date);
CREATE INDEX IF NOT EXISTS idx_visitor_daily_visits_session ON public.visitor_daily_visits(session_id);

-- 3. Row Level Security (RLS)
ALTER TABLE public.visitor_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_daily_visits ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Admins can view visitor sessions" ON public.visitor_sessions;
DROP POLICY IF EXISTS "Admins can view visitor daily visits" ON public.visitor_daily_visits;

-- RLS: Only Admins can view analytics records directly
CREATE POLICY "Admins can view visitor sessions" ON public.visitor_sessions
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE id = auth.uid() 
            AND (raw_app_meta_data->>'is_admin')::boolean = true
        ) OR 
        (SELECT is_admin FROM public.profiles WHERE id = auth.uid())
    );

CREATE POLICY "Admins can view visitor daily visits" ON public.visitor_daily_visits
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE id = auth.uid() 
            AND (raw_app_meta_data->>'is_admin')::boolean = true
        ) OR 
        (SELECT is_admin FROM public.profiles WHERE id = auth.uid())
    );

-- 4. Storefront Heartbeat RPC (SECURITY DEFINER)
-- Allows anonymous and authenticated visitors to record/update their own heartbeat and daily visit
CREATE OR REPLACE FUNCTION public.record_visitor_heartbeat(p_session_id TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_today DATE := (timezone('utc'::text, now()))::date;
BEGIN
    IF p_session_id IS NULL OR trim(p_session_id) = '' THEN
        RETURN;
    END IF;

    -- Upsert session
    INSERT INTO public.visitor_sessions (session_id, first_seen_at, last_seen_at)
    VALUES (p_session_id, timezone('utc'::text, now()), timezone('utc'::text, now()))
    ON CONFLICT (session_id) DO UPDATE
    SET last_seen_at = timezone('utc'::text, now());

    -- Upsert daily visit (at most once per calendar day)
    INSERT INTO public.visitor_daily_visits (session_id, visit_date)
    VALUES (p_session_id, v_today)
    ON CONFLICT (session_id, visit_date) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.record_visitor_heartbeat(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_visitor_heartbeat(TEXT) TO anon, authenticated, service_role;

-- 5. Protected Admin Analytics Aggregation RPC (SECURITY DEFINER)
-- Checks admin authorization and returns active visitors + continuous daily visit series
CREATE OR REPLACE FUNCTION public.get_admin_visitor_analytics(p_days INTEGER DEFAULT 7)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_is_admin BOOLEAN := false;
    v_current_visitors INTEGER := 0;
    v_daily_visits json;
    v_start_date DATE;
    v_end_date DATE;
    v_clamped_days INTEGER;
BEGIN
    -- Admin authorization check
    SELECT (
        (auth.role() = 'service_role') OR
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE id = auth.uid() 
            AND (raw_app_meta_data->>'is_admin')::boolean = true
        ) OR 
        (SELECT is_admin FROM public.profiles WHERE id = auth.uid())
    ) INTO v_is_admin;

    IF v_is_admin IS NOT TRUE THEN
        RAISE EXCEPTION 'Access denied: administrator privileges required.';
    END IF;

    -- Clamp days to range [1, 90]
    v_clamped_days := LEAST(GREATEST(COALESCE(p_days, 7), 1), 90);
    v_end_date := (timezone('utc'::text, now()))::date;
    v_start_date := v_end_date - (v_clamped_days - 1);

    -- 1. Active sessions within 5 minutes
    SELECT COUNT(DISTINCT session_id)
    INTO v_current_visitors
    FROM public.visitor_sessions
    WHERE last_seen_at >= (timezone('utc'::text, now()) - interval '5 minutes');

    -- 2. Continuous daily visits in date order
    SELECT json_agg(
        json_build_object(
            'date', to_char(d.day, 'YYYY-MM-DD'),
            'visits', COALESCE(v.visit_count, 0)
        ) ORDER BY d.day ASC
    )
    INTO v_daily_visits
    FROM (
        SELECT generate_series(v_start_date::timestamp, v_end_date::timestamp, '1 day'::interval)::date AS day
    ) d
    LEFT JOIN (
        SELECT visit_date, COUNT(DISTINCT session_id) AS visit_count
        FROM public.visitor_daily_visits
        WHERE visit_date >= v_start_date AND visit_date <= v_end_date
        GROUP BY visit_date
    ) v ON d.day = v.visit_date;

    RETURN json_build_object(
        'current_visitors', COALESCE(v_current_visitors, 0),
        'daily_visits', COALESCE(v_daily_visits, '[]'::json)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.get_admin_visitor_analytics(INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_admin_visitor_analytics(INTEGER) TO authenticated, service_role;
