-- Migration: Create coupons and coupon_users tables
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('percentage', 'fixed', 'buy_x_get_y', 'percentage_discount')) NOT NULL,
    value NUMERIC,
    buy_qty INTEGER,
    free_qty INTEGER,
    min_subtotal NUMERIC,
    min_quantity INTEGER,
    description TEXT NOT NULL,
    min_order_value NUMERIC,
    discount_percent NUMERIC,
    is_active BOOLEAN DEFAULT true NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    max_redemptions INTEGER,
    current_redemptions INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create relationship table for user-specific coupons
CREATE TABLE IF NOT EXISTS public.coupon_users (
    coupon_id BIGINT REFERENCES public.coupons(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (coupon_id, user_id)
);

-- Enable RLS
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_users ENABLE ROW LEVEL SECURITY;

-- Create Policies for coupons
CREATE POLICY "Anyone can view coupons" ON public.coupons
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage coupons" ON public.coupons
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_admin = true
        )
    );

-- Create Policies for coupon_users
CREATE POLICY "Users can view their own eligibility" ON public.coupon_users
    FOR SELECT USING (auth.uid() = user_id OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND is_admin = true
    ));

CREATE POLICY "Admins can manage coupon users" ON public.coupon_users
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_admin = true
        )
    );
